# SITE CONFIGURATION
baseurl: ""
url: "https://sylhare.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Type on Strap                                    # site's title
description: "A website with blog posts and pages"      # used by search engines
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Change <code>header_text</code> in <code>_config.yml</code>  # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                       # Your discus shortname for comments
  cusdis_app_id:                                          # Your cusdis data-app-id
  utterances:                                             # just fill out the below parts, and this is important. you MUST give a repo name like sylhare/Type-on-Strap. For more info, go to https://utteranc.es
    repo:                                                 # your comments repo name
    issue-term:                                           # your issue term. for info, go to https://utteranc.es
    theme:                                                # GitHub Light/Dark, type it as github-[light/dark] and choose only one of them.
  
# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
