# SITE CONFIGURATION
url: "https://talpio.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Blog de Talpio
  avatar: assets/img/triangle.svg
  favicon: 
  gravatar: # Email MD5 hash
  description: "El blog de Talpio" # used by search engines
  disqus_shortname: 

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Bienvenido a mi <code>blog de pruebas</code> <br> de códigos.</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Desarrollado por <a href="https://jekyllrb.com/">Jekyll</a> con <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: false
  email_address: "talpiod@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "Talpio"
  flickr:
  gitlab:
  github: "Talpio"
  google_plus:
  instagram: "talpiod"
  keybase:
  linkedin: "https://www.linkedin.com/in/delgadojesus"  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "Talpio"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: false
  search: true
  tags: false
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Siguiente publicación"
  str_previous_post: "Publicación anterior"
  str_next_page: "Siguiente"
  str_previous_page: "Anterior"
  str_continue_reading: "Continuar leyendo"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
