# SITE CONFIGURATION
baseurl: ""
url: "https://nutbrown.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Nutbrown.io
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: "adfbe6d61be40c206a78d553b848bb16"
  description: "Personal tech-themed blog for Stephen Nutbrown. Mostly featuring AWS cloud projects written in Java, Javascript, Python, Ruby, Groovy and whatever else is necessary (php is never necessary)." # used by search engines

  # Header and footer text
  header_text: >
     <p>A personal tech-themed blog, mostly featuring AWS cloud projects written in Java, Javascript, Python, Ruby, Groovy and whatever else is necessary <br/>(php is never necessary).</p>

     <p>Got an idea or improvement? Pull requests or bug reports are welcome <a href="https://github.com/NutterzUK/nutbrown">here</a>.</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Gratefully powered by <a href="https://jekyllrb.com/">Jekyll</a>, using <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: false
  email_address: "stephen@nutbrown.io"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "NutterzUK/nutbrown"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/stephen-nutbrown-59a94838/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam: "NutterzUK"
  tumblr:
  twitter: "nutterzuk"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-55663428-6"
  disqus_shortname: "nutbrown-io"
  katex: false # Enable if using math markup
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
