name: Type-on-strap CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ruby:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install
        run: bundle install
      - name: Build jekyll site
        run: bundle exec jekyll build
      - name: Start Jekyll site
        run: timeout 10s bundle exec jekyll serve
        continue-on-error: true
      - name: Build the gem
        continue-on-error: true
        run: |
          gem build *.gemspec
          echo `find . -name "*.gem" | tail -1 | awk -F"[/]" '{print $2}'`
      - name: Install theme gems
        run: |
          gem cleanup type-on-strap
          gem install type-on-strap --source "https://rubygems.org" 
          gem install jekyll-theme-type-on-strap --source "https://rubygems.org"
      - name: GPR
        run: |
          gem cleanup type-on-strap
          gem install type-on-strap --version "2.4.11" --source "https://rubygems.pkg.github.com/sylhare"
